#Auteur : COUTAND Bastien
version: '3.8'
services:
    app:
      build: 
        context: ./app-container
        dockerfile: Dockerfile
      restart: always
      ports:
        - "8000:8000"